
## Title: Passenger Data Encoding & Feature Scaling
### Objective: Prepare dataset for ML model using encoding and scaling techniques.

In [18]:
# Import & create Dataset

import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
df

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

# TASK 1: CATEGORICAL ENCODING

In [19]:
# 2.1 Gender → Label Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

Conclusion: The ML data has been converted into numeric format.

In [20]:
# 2.2 City → One Hot Encoding

df = pd.get_dummies(df, columns=['City'], drop_first=True)

Conclusion: The model does not get confused and there is no incorrect priority order.

In [21]:
# 2.3 Size → Ordered Label Encoding

size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)

Conclusion: The order is preserved and the ML model correctly understands the size hierarchy.

# TASK 2: FEATURE SCALING

###Purpose: Scaling ensures fair comparison between features

In [22]:
# Apply Scaling (StandardScaler)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])
df

# Reason for using StandardScaler:
# - Fare column contains outlier (450)
# - StandardScaler normalizes data (mean = 0, std = 1)
# - Helps ML model treat Age and Fare equally

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -1.004168 -0.921155       False         True
1       0     2  0.540706  0.729972        True        False
2       0     1 -0.463462 -0.515615       False        False
3       1     2  1.699361  1.598986       False         True
4       0     0 -0.772437 -0.892188        True        False

In [23]:
df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -1.004168 -0.921155       False         True
1       0     2  0.540706  0.729972        True        False
2       0     1 -0.463462 -0.515615       False        False
3       1     2  1.699361  1.598986       False         True
4       0     0 -0.772437 -0.892188        True        False